src/main/java/com/nbc/newsfeeds/domain/member/controller/MemberController.java, src/main/java/com/nbc/newsfeeds/domain/member/entity/Member.java, src/main/java/com/nbc/newsfeeds/domain/member/repository/MemberRepository.java, src/main/java/com/nbc/newsfeeds/domain/member/service/MemberService.java
=> Feature : member init

build.gradle, src/main/java/com/nbc/newsfeeds/audit/BaseEntity.java, src/main/java/com/nbc/newsfeeds/common/config/JpaConfig.java, src/main/java/com/nbc/newsfeeds/common/config/SecurityConfig.java
security 기본 설정과 jpa 설정, BaseEntity 추가
=> Feature : config 추가

build.gradle, src/main/java/com/nbc/newsfeeds/common/config/SecurityConfig.java, src/main/java/com/nbc/newsfeeds/common/config/SwaggerConfig.java, src/main/java/com/nbc/newsfeeds/common/filter/JwtAuthenticationFilter.java, src/main/java/com/nbc/newsfeeds/common/filter/JwtExceptionFilter.java, src/main/java/com/nbc/newsfeeds/common/jwt/JwtTokenProvider.java, src/main/java/com/nbc/newsfeeds/common/jwt/constant/JwtConstants.java, src/main/java/com/nbc/newsfeeds/common/jwt/constant/TokenExpiredConstant.java, src/main/java/com/nbc/newsfeeds/common/jwt/dto/TokenDto.java, src/main/java/com/nbc/newsfeeds/domain/member/controller/AuthController.java, src/main/java/com/nbc/newsfeeds/domain/member/controller/MemberController.java, src/main/java/com/nbc/newsfeeds/domain/member/dto/MemberAuthDto.java, src/main/java/com/nbc/newsfeeds/domain/member/dto/request/MemberCreateDto.java, src/main/java/com/nbc/newsfeeds/domain/member/dto/request/MemberSignInDto.java, src/main/java/com/nbc/newsfeeds/domain/member/dto/response/MemberDto.java, src/main/java/com/nbc/newsfeeds/domain/member/entity/Member.java, src/main/java/com/nbc/newsfeeds/domain/member/repository/MemberRepository.java, src/main/java/com/nbc/newsfeeds/domain/member/service/MemberService.java, src/main/resources/application.properties
security 설정 추가, token 발행 추가, 유저 생성, 로그인 추가, filter 추가
* 현재 refresh token은 기능을 하지 않고 발행만 하고 있음!
* custom exception 정의가 되지 않아서 임시로 RuntimeException을 넣어줌
=> Feature : 유저 생성, 로그인

src/main/java/com/nbc/newsfeeds/common/response/CommonResponse.java, src/main/java/com/nbc/newsfeeds/common/response/CommonResponses.java, src/main/java/com/nbc/newsfeeds/common/response/ResponseCode.java
=> Feature : 공통 응답

src/main/java/com/nbc/newsfeeds/domain/friend/constant/FriendshipStatus.java, src/main/java/com/nbc/newsfeeds/domain/friend/controller/FriendController.java, src/main/java/com/nbc/newsfeeds/domain/friend/entity/Friendship.java, src/main/java/com/nbc/newsfeeds/domain/friend/entity/FriendshipStatus.java, src/main/java/com/nbc/newsfeeds/domain/friend/model/request/CursorPageRequest.java, src/main/java/com/nbc/newsfeeds/domain/friend/model/request/RespondToFriendRequest.java, src/main/java/com/nbc/newsfeeds/domain/friend/model/response/CursorPage.java, src/main/java/com/nbc/newsfeeds/domain/friend/model/response/CursorPageResponse.java, src/main/java/com/nbc/newsfeeds/domain/friend/model/response/FriendRequestResponse.java, src/main/java/com/nbc/newsfeeds/domain/friend/model/response/FriendRequestsResponse.java, src/main/java/com/nbc/newsfeeds/domain/friend/model/response/FriendsResponse.java, src/main/java/com/nbc/newsfeeds/domain/friend/repository/FriendshipRepository.java, src/main/java/com/nbc/newsfeeds/domain/friend/service/FriendService.java
임시로 런타임 예외를 던지도록 구현했습니다.
인증 및 회원 기능 완료 후 세부적인 부분 수정 예정입니다.
커서 기반 페이지네이션용 DTO는 공통으로 빼는 것이 좋지만 혹시 모를 충돌을 대비해 나중에 리팩토링으로 빼겠습니다.
=> Featrue : 친구 심화 기능

src/main/java/com/nbc/newsfeeds/common/exception/BaseException.java, src/main/java/com/nbc/newsfeeds/common/exception/dto/ValidationError.java, src/main/java/com/nbc/newsfeeds/common/exception/handler/GlobalExceptionHandler.java
커스텀 exception 기본과 exception handler 정의
=> Feature : 예외 처리

src/main/java/com/nbc/newsfeeds/common/config/SecurityConfig.java, src/main/java/com/nbc/newsfeeds/common/config/SwaggerConfig.java, src/main/java/com/nbc/newsfeeds/common/filter/AccessTokenFilter.java, src/main/java/com/nbc/newsfeeds/common/filter/BaseJwtTokenFilter.java, src/main/java/com/nbc/newsfeeds/common/filter/RefreshTokenFilter.java, src/main/java/com/nbc/newsfeeds/common/filter/constant/FilterConstants.java, src/main/java/com/nbc/newsfeeds/common/jwt/constant/JwtConstants.java, src/main/java/com/nbc/newsfeeds/common/jwt/core/JwtGenerator.java, src/main/java/com/nbc/newsfeeds/common/jwt/core/JwtParser.java, src/main/java/com/nbc/newsfeeds/common/jwt/core/JwtService.java, src/main/java/com/nbc/newsfeeds/common/jwt/exception/JwtTokenException.java, src/main/java/com/nbc/newsfeeds/common/jwt/exception/JwtTokenExceptionCode.java, src/main/java/com/nbc/newsfeeds/common/redis/service/RedisService.java, src/main/java/com/nbc/newsfeeds/domain/member/auth/MemberAuth.java, src/main/java/com/nbc/newsfeeds/domain/member/constant/MemberResponseCode.java, src/main/java/com/nbc/newsfeeds/domain/member/controller/AuthController.java, src/main/java/com/nbc/newsfeeds/domain/member/dto/MemberAuthDto.java, src/main/java/com/nbc/newsfeeds/domain/member/dto/request/MemberCreateDto.java, src/main/java/com/nbc/newsfeeds/domain/member/dto/request/MemberDeleteDto.java, src/main/java/com/nbc/newsfeeds/domain/member/dto/request/MemberSignInDto.java, src/main/java/com/nbc/newsfeeds/domain/member/dto/response/MemberDto.java, src/main/java/com/nbc/newsfeeds/domain/member/entity/Member.java, src/main/java/com/nbc/newsfeeds/domain/member/exception/MemberException.java, src/main/java/com/nbc/newsfeeds/domain/member/repository/MemberRepository.java, src/main/java/com/nbc/newsfeeds/domain/member/service/MemberService.java
임의로 반환하던 응답값들을 공통 응답객체로 반환, 요청 dto에 valid 추가
=> Refactor : 유저 서비스 응답값 수정, dto valid 추가

src/main/java/com/nbc/newsfeeds/domain/heart/entity/Heart.java, src/main/java/com/nbc/newsfeeds/domain/heart/exception/HeartException.java, src/main/java/com/nbc/newsfeeds/domain/heart/repository/HeartRepository.java, src/main/java/com/nbc/newsfeeds/domain/heart/service/HeartServiceImpl.java, src/test/java/com/nbc/newsfeeds/domain/heart/service/HeartServiceImplTest.java
오타 난 거 수정했고, 테스트 완료하였습니다. request 확인부탁드립니다.
=> chore : 오타 수정 및 엔티티 생성자 어노테이션 추가

.editorconfig, .gitattributes
지금 프로젝트의 코드들이 CRLF로 변경되어 있어서 강제적으로 LF로 변경되도록 설정 파일 추가
=> Chore : LF 설정 강제

src/main/java/com/nbc/newsfeeds/domain/member/auth/MemberAuth.java, src/main/java/com/nbc/newsfeeds/domain/member/dto/request/MemberCreateDto.java, src/main/java/com/nbc/newsfeeds/domain/member/dto/request/MemberDeleteDto.java, src/main/java/com/nbc/newsfeeds/domain/member/dto/request/MemberSignInDto.java
현재 security에서 사용되는 부분이 없기 때문에 코드 제거
@notblank 어노테이션이 null 체크도 함께 해주기 때문에 해당 어노테이션 제거
=> Refactor : UserDetails 구현 제거,  @NotNull 어노테이션 제거 

src/main/java/com/nbc/newsfeeds/domain/member/controller/AuthController.java, src/main/java/com/nbc/newsfeeds/domain/member/dto/request/MemberDeleteDto.java, src/main/java/com/nbc/newsfeeds/domain/member/dto/response/AccessTokenDto.java, src/main/java/com/nbc/newsfeeds/domain/member/dto/response/MemberDto.java, src/main/java/com/nbc/newsfeeds/domain/member/service/MemberService.java, src/test/java/com/nbc/newsfeeds/domain/member/controller/AuthControllerTest.java, src/test/java/com/nbc/newsfeeds/domain/member/service/MemberServiceTest.java
테스트하기에 용이하게 하기 위해서 String으로 반환하던 부분을 객체로 반환하도록 변경, 테스트 케이스로 사용하기 위해서 dto에 생성자 추가
성공 케이스만 단위테스트 진행, 반환값 변경에 따라 테스트 코드 수정
=> Test : member controller 단위 테스트

src/main/java/com/nbc/newsfeeds/domain/member/constant/MemberResponseCode.java, src/main/java/com/nbc/newsfeeds/domain/member/controller/AuthController.java, src/main/java/com/nbc/newsfeeds/domain/member/controller/ProfileController.java, src/main/java/com/nbc/newsfeeds/domain/member/dto/request/MemberSignUpDto.java, src/main/java/com/nbc/newsfeeds/domain/member/dto/request/MemberUpdateDto.java, src/main/java/com/nbc/newsfeeds/domain/member/dto/request/MemberWithdrawDto.java, src/main/java/com/nbc/newsfeeds/domain/member/dto/response/MemberDto.java, src/main/java/com/nbc/newsfeeds/domain/member/entity/Member.java, src/main/java/com/nbc/newsfeeds/domain/member/service/MemberService.java, src/test/java/com/nbc/newsfeeds/domain/member/controller/AuthControllerTest.java, src/test/java/com/nbc/newsfeeds/domain/member/controller/ProfileControllerTest.java, src/test/java/com/nbc/newsfeeds/domain/member/service/MemberServiceTest.java
requestDto 네이밍 변경
유저 수정, 프로필 조회 -> 본인, 타인 정보 다름
requestDto 네이밍 변경에 따라 테스트 코드 수정
유저 수정, 프로필 조회 service와 controller 단위 테스트
=> Feat : 유저 수정, 프로필 조회

src/main/java/com/nbc/newsfeeds/domain/comment/controller/CommentController.java, src/main/java/com/nbc/newsfeeds/domain/comment/dto/request/CommentCreateRequest.java, src/main/java/com/nbc/newsfeeds/domain/comment/dto/request/CommentUpdateRequest.java, src/main/java/com/nbc/newsfeeds/domain/comment/entity/Comment.java, src/main/java/com/nbc/newsfeeds/domain/comment/repository/CommentRepository.java, src/main/java/com/nbc/newsfeeds/domain/comment/service/CommentService.java, src/main/java/com/nbc/newsfeeds/domain/feed/controller/FeedController.java, src/test/java/com/nbc/newsfeeds/domain/comment/service/CommentServiceTest.java
=> 댓글 테스트코드 작성

README.md
기능 부분에 본인이 맡은 기능 내용 추가해주시면 감사하겠습니다!
추가로 본인이 겪은 트러블 슈팅 notion링크 걸어 두었으니 작성해 주시면 감사합니다!
=> Docs : README 작성

src/main/java/com/nbc/newsfeeds/common/filter/BaseJwtTokenFilter.java, src/main/java/com/nbc/newsfeeds/common/filter/JwtExceptionFilter.java, src/main/java/com/nbc/newsfeeds/common/jwt/core/JwtGenerator.java, src/main/java/com/nbc/newsfeeds/common/jwt/core/JwtParser.java, src/main/java/com/nbc/newsfeeds/common/redis/service/RedisService.java, src/main/java/com/nbc/newsfeeds/domain/member/service/MemberService.java
=> Comment : 유저, 프로필 기능, 인증 기능 주석 추가

src/main/java/com/nbc/newsfeeds/common/filter/constant/FilterConstants.java, src/main/java/com/nbc/newsfeeds/common/jwt/constant/JwtConstants.java
=> Refactor : 상수 클래스에 생성자 추가

src/main/java/com/nbc/newsfeeds/common/filter/BaseJwtTokenFilter.java, src/main/java/com/nbc/newsfeeds/common/filter/JwtExceptionFilter.java, src/main/java/com/nbc/newsfeeds/common/jwt/core/JwtGenerator.java, src/main/java/com/nbc/newsfeeds/common/jwt/core/JwtParser.java, src/main/java/com/nbc/newsfeeds/common/redis/service/RedisService.java, src/main/java/com/nbc/newsfeeds/domain/member/service/MemberService.java
=> Comment : 작성자 이름 추가

src/main/java/com/nbc/newsfeeds/common/jwt/constant/TokenExpiredConstant.java, src/main/java/com/nbc/newsfeeds/common/jwt/core/JwtParser.java, src/main/java/com/nbc/newsfeeds/common/jwt/core/JwtService.java
로그 아웃 시 access token을 redis에 black list로 저장할 때 access token의 잔여 ttl을 계산하여 넣어주도록 변경
=> Refactor : black list ttl 변경

src/main/java/com/nbc/newsfeeds/common/exception/handler/GlobalExceptionHandler.java, src/main/java/com/nbc/newsfeeds/common/response/CommonResponse.java
날짜 입력 시 잘못된 값을 입력 했을 경우 handling하는 메서드 추가
=> Feature : 예외 handling 추가

src/main/java/com/nbc/newsfeeds/common/aop/LogAop.java, src/main/resources/logback-spring.xml
어떤 controller의 메서드가 실행 되었는지와 파라미터, 실행 후 반환 타입을 log로 출력
=> Feature : controller 호출 시 log 추가

src/main/java/com/nbc/newsfeeds/common/redis/service/RedisService.java, src/test/java/com/nbc/newsfeeds/domain/member/controller/ProfileControllerTest.java
trasaction이 java 기본으로 import 되있던 것을 spring framework가 제공하는 것으로 변경, 내부 로직 변경에 따라 테스트 코드 수정
=> Refactor : import 변경, 테스트 코드 수정
